require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/weather_reports", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WeatherReport. As you add validations to WeatherReport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WeatherReport.create! valid_attributes
      get weather_reports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      weather_report = WeatherReport.create! valid_attributes
      get weather_report_url(weather_report)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_weather_report_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      weather_report = WeatherReport.create! valid_attributes
      get edit_weather_report_url(weather_report)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WeatherReport" do
        expect {
          post weather_reports_url, params: { weather_report: valid_attributes }
        }.to change(WeatherReport, :count).by(1)
      end

      it "redirects to the created weather_report" do
        post weather_reports_url, params: { weather_report: valid_attributes }
        expect(response).to redirect_to(weather_report_url(WeatherReport.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WeatherReport" do
        expect {
          post weather_reports_url, params: { weather_report: invalid_attributes }
        }.to change(WeatherReport, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post weather_reports_url, params: { weather_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested weather_report" do
        weather_report = WeatherReport.create! valid_attributes
        patch weather_report_url(weather_report), params: { weather_report: new_attributes }
        weather_report.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the weather_report" do
        weather_report = WeatherReport.create! valid_attributes
        patch weather_report_url(weather_report), params: { weather_report: new_attributes }
        weather_report.reload
        expect(response).to redirect_to(weather_report_url(weather_report))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        weather_report = WeatherReport.create! valid_attributes
        patch weather_report_url(weather_report), params: { weather_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested weather_report" do
      weather_report = WeatherReport.create! valid_attributes
      expect {
        delete weather_report_url(weather_report)
      }.to change(WeatherReport, :count).by(-1)
    end

    it "redirects to the weather_reports list" do
      weather_report = WeatherReport.create! valid_attributes
      delete weather_report_url(weather_report)
      expect(response).to redirect_to(weather_reports_url)
    end
  end
end
